yolo: https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8x.pt
tracking:
  track_high_thresh: 0.3
  track_low_thresh: 0.1
  new_track_thresh: 0.4
  track_buffer: 20
  proximity_thresh: 0.5
  appearance_thresh: 0.25
  cmc_method: sparseOptFlow
  min_box_area: 10.0
  name: exp
  ablation: False
  with_reid: False
  mot20: False
  match_thresh: 0.7

th_conf: 0.05
th_iou: 0.95
