yolo:
  weights: https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8m.pt
  th_conf: 0.05
  th_iou: 0.95
  max_area: 40000
  min_area: 10

tracking:
  track_high_thresh: 0.3
  track_low_thresh: 0.05
  new_track_thresh: 0.05
  track_buffer: 20
  proximity_thresh: 0.5
  appearance_thresh: 0.25
  cmc_method: sparseOptFlow
  name: exp
  ablation: False
  with_reid: True
  mot20: False
  match_thresh: 0.5
